[project]
name = "tweedledum"
requires-python = ">=3.6"
version = "1.1.2b"

[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "cmake>=3.18",
    "ninja",
    "scikit-build>=0.12.0",
]
